apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_URLS: http://+:80;http://+:7777
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitps
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=auctions
  IdentityServiceUrl: http://identity-svc
  Kestrel__Endpoints__Grpc__Protocols: Http2
  Kestrel__Endpoints__Grpc__Url: http://+:7777
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: Http://+:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitps
  ConnectionStrings__MongoDbConnection: mongodb://root:mongops@mongo-clusterip
  AuctionServiceUrl: http://auction-clusterip
