apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_URLS: http://+:80;http://+:7777
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitps
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=auctions
  IdentityServiceUrl: http://identity-clusterip
  Kestrel__Endpoints__Grpc__Protocols: Http2
  Kestrel__Endpoints__Grpc__Url: http://+:7777
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: Http://+:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitps
  ConnectionStrings__MongoDbConnection: mongodb://root:mongops@mongo-clusterip
  AuctionServiceUrl: http://auction-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bid-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitps
  ConnectionStrings__BidDbConnection: mongodb://root:mongops@mongo-clusterip
  IdentityServiceUrl: http://identity-clusterip
  GrpcAution: http://auction-clusterip:7777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Username: rabbit
  RabbitMq__Password: rabbitps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  ClientApp: https://app.cars.com
  IdentityServiceUrl: http://identity-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:
  ASPNETCORE_URLS: http://+:443
  ConnectionStrings__DefaultConnection: Server=postgres-clusterip:5432;User Id=postgres;Password=postgrespw;Database=identity
  IssuerUri: https://id.cars.com
  ClientApp: https://app.cars.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  NEXTAUTH_SECRET: somethingsecret
  NEXTAUTH_URL: https://app.cars.com
  NEXTAUTH_URL_INTERNAL: http://webapp-clusterip:3000
  API_URL: http://gateway-clusterip/
  ID_URL: https://id.cars.com
  ID_URL_INTERNAL: http://identity-clusterip
  NOTIFY_URL: https://api.cars.com/notifications
